---
- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present

# Note: Homebrew casks (GUI applications) are now managed by the gui_apps role
