---
# macOS-specific shell setup

- name: Get Homebrew prefix
  command: brew --prefix
  register: homebrew_prefix
  changed_when: false
  check_mode: false

- name: Set Homebrew prefix fact
  set_fact:
    brew_prefix: "{{ homebrew_prefix.stdout }}"

- name: Create shell configuration directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_env.HOME }}/.local/share"
    - "{{ ansible_env.HOME }}/.local/share/zinit"

- name: Install Zinit (Zsh plugin manager)
  include_tasks: zinit.yml

- name: Install nushell via Homebrew
  community.general.homebrew:
    name: nushell
    state: present

- name: Verify nushell installation
  command: which nu
  register: nu_location
  ignore_errors: true

- name: Create nushell config directory (for future use)
  file:
    path: "{{ ansible_env.HOME }}/.config/nushell"
    state: directory
    mode: "0755"
  when: nu_location.rc == 0

- name: Deploy shell configuration files
  include_tasks: config.yml
